# Generated by Django 5.1.3 on 2025-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_withdrawalfromcompoundingprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyertransaction',
            name='method',
            field=models.CharField(choices=[('Bkash', 'BKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], default='Bkash', max_length=10),
        ),
    ]
