# Generated by Django 5.1.3 on 2025-03-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_buyertransaction_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutDetails',
            new_name='CheckoutDetail',
        ),
        migrations.RenameModel(
            old_name='WithdrawalRequest',
            new_name='WithdrawalFromCashupBalance',
        ),
    ]
