# Generated by Django 5.1.3 on 2025-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_rename_checkoutdetails_checkoutdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='cashup_owing_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
