# Generated by Django 5.1.3 on 2025-03-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_transferhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='method',
        ),
    ]
