# Generated by Django 5.1.3 on 2025-03-09 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_deposithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DepositHistory',
        ),
    ]
