# Generated by Django 5.1.3 on 2025-03-10 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_slider_transferhistoryofcashupowingdps'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalfromcashupbalance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawalfromcompoundingprofit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawalfrommainbalance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
