# Generated by Django 5.1.3 on 2025-03-10 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_withdrawalfromcashupbalance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupdeposit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_timestamp', models.DateTimeField(auto_now_add=True)),
                ('cashup_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cashupdeposit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
