# Generated by Django 5.1.3 on 2025-03-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_cashupdeposit_updated_by_profithistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfitHistory',
            new_name='CashupProfitHistory',
        ),
    ]
