# Generated by Django 5.1.3 on 2025-03-10 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_cashupowingprofithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
