# Generated by Django 5.1.3 on 2025-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_cashupowingdeposit_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferhistoryofcashup',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferhistoryofcashupowingdps',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
