# Generated by Django 5.1.3 on 2025-03-10 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_alter_transferhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyertransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
