# Generated by Django 5.1.3 on 2025-03-10 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_alter_buyertransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashupowingprofithistory',
            name='change_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cashupprofithistory',
            name='change_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transferhistoryofcashup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transferhistoryofcashupowingdps',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
