# Generated by Django 5.1.3 on 2025-03-11 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_transferhistory_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalfromcashupbalance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawalfromcompoundingprofit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawalfrommainbalance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
