# Generated by Django 5.1.3 on 2025-03-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_alter_cashupowingdeposit_requested_cashup_owing_main_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_membership_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashupowingdeposit',
            name='requested_cashup_owing_main_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
