# Generated by Django 5.1.3 on 2025-03-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_purchase_total_membership_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashupowingprofithistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cashupprofithistory',
            name='updated_by',
        ),
    ]
