# Generated by Django 5.1.3 on 2025-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_cashupowingprofithistory_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_rate',
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
