# Generated by Django 5.1.3 on 2025-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_remove_item_discount_rate_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalfrommainbalance',
            name='method',
            field=models.CharField(choices=[('Bkash', 'BKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], default='Bkash', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawalfrommainbalance',
            name='withdraw_number',
            field=models.CharField(default='000', max_length=20),
        ),
    ]
