# Generated by Django 5.1.3 on 2025-03-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0033_cashupdeposit_affiliate_profit_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='referral_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.referralcode'),
        ),
    ]
