# Generated by Django 5.1.3 on 2025-03-15 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_withdrawalfromdailyprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (with or without country code).', regex='^(?:\\+8801[3-9]{1}[0-9]{8}|01[3-9]{1}[0-9]{8})$')]),
        ),
    ]
