# Generated by Django 5.1.3 on 2025-03-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0041_buyerotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to='myapi.referralcode'),
        ),
    ]
