# Generated by Django 5.1.3 on 2025-03-16 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0042_buyer_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (with or without country code).', regex='^(?:\\+8801[3-9]{1}[0-9]{8}|01[3-9]{1}[0-9]{8})$')])),
            ],
        ),
    ]
