# Generated by Django 5.1.3 on 2025-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0043_companynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('logo_url', models.CharField(blank=True, help_text='Image of the product', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sponsoredby',
            name='brand_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
