# Generated by Django 5.1.3 on 2025-03-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0044_productadslider_sponsoredby_brand_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='referral_code',
        ),
    ]
