# Generated by Django 5.1.3 on 2025-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0045_remove_buyer_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupdeposit',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='monthly_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
