# Generated by Django 5.1.3 on 2025-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0046_cashupdeposit_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashupowingdeposit',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
