# Generated by Django 5.1.3 on 2025-03-20 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0049_mobilerecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashupDepositMonthlyCompounding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compounding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_compounding_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monhly_compounding_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_prpfit_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compounding_profit_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('monthly_reset_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CashupDepositMonthlyCompounding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashupMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_profit_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('monthly_reset_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CashupMonthly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
