# Generated by Django 5.1.3 on 2025-03-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0050_cashupdepositmonthlycompounding_cashupmonthly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashupdepositmonthlycompounding',
            old_name='deposit_prpfit_withdraw',
            new_name='deposit_profit_withdraw',
        ),
        migrations.RenameField(
            model_name='cashupdepositmonthlycompounding',
            old_name='monhly_compounding_profit',
            new_name='monthly_compounding_profit',
        ),
    ]
