# Generated by Django 5.1.3 on 2025-03-20 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0051_rename_deposit_prpfit_withdraw_cashupdepositmonthlycompounding_deposit_profit_withdraw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashupmonthly',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CashUpDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_profit_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('monthly_reset_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CashupDaily', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
