# Generated by Django 5.1.3 on 2025-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0052_alter_cashupmonthly_created_at_cashupdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupmonthly',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
