# Generated by Django 5.1.3 on 2025-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0054_cashupdepositmonthlycompounding_profit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupdaily',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdaily',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
